some problems with realasing mongodb-repository
imakiri/gorum pull request #5
Opened 2021-04-17 11:32 UTC by Dponya

Проблема с NewAvatarService(dbType string, db *mongo.Database) (Avatar, error) в content.go. Если добавлять через switch-case postgres и mongodb, то придется и в аргументы конструктора доставлять 2 инстанта: mongodb и sql.db

2021-04-17 12:52 UTC, imakiri requested changes

2021-04-17 12:52 UTC, imakiri commented on mongodb/avatar.go
> +type AvatarMongo struct {
Предполагается что пакет mongodb будет содержать только функции данных, какое либо структурирование - в пакете data и content

2021-04-17 12:52 UTC, imakiri commented on mongodb/avatar.go
> +type AvatarMongo struct {
postgres/avatar.go пример этих функций, только работающих с postgres базой
content/avatar.go:avatar пример структурирования - объединение функций пакета postgres в сервис данных

2021-04-17 12:52 UTC, imakiri commented on content/content.go
> +func NewAvatarService(dbType string, db *mongo.Database) (Avatar, error) {
NewAvatarService(dbType string) (Avatar, error)
switch dbType {
	case MONGODB:
                var s = new(serviceMongo)
                s.db = // new mongo db connection 
		return s, nil
}

2021-04-17 13:25 UTC, imakiri commented on content/content.go
> +func NewAvatarService(dbType string, db *mongo.Database) (Avatar, error) {
NewAvatarService по аргументу dbType должен сам решить что нужно инициализировать, и собственно выполнить эту инициализацию т.е. внутри себя создать sqlx.DB и\или mongo.Database, а не получать из вне

2021-04-18 07:54 UTC, Dponya commented
Прописал иниты для клиента и коннекшена mongodb. Также вернул назад удаленный AuthService. Комментарии в коде - все мои вопросы.

2021-04-19 12:12 UTC, closed without merging